# populate slots
two_month_appointments = ""
MIN_WEEK = 0
MAX_WEEK = 7
current_week_index = 0
appointment_type_selected = ""
current_physician_id = 0
get_user_selected_appointments = ""
appointment_type = ""
